version: '3'
services:
  workspace:
    build: .
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - ../:/usr/src/app
      - node_modules:/usr/src/app/node_modules
volumes:
  node_modules:
